Sno=int(input("Enter student number:"))
name=input("Enter student name:")
group=input("Enter student group")
gender=input("Enter gender of the student")
address=input("Enter student address")
phno=int(input("Enter student phone number:"))
print("Sno : ",Sno)
print("Name : ",name)
print("Group : ",group)
print("Gender : ",gender)
print("Address : ",address)
print("Phone number : ",phno)
